name: Go CI with Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to latest version

      - name: Update packages list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y libgpgme-dev

      - name: Set up Go 1.20.5
        uses: actions/setup-go@v4 # Updated to latest version
        with:
          go-version: 1.20.5

      - name: Build
        run: |
          go build -o longtea_${GITHUB_REF#refs/tags/}

      - name: Check if file exists
        id: check_file
        run: |
          if [ -f "longtea_${GITHUB_REF#refs/tags/}" ]; then
            echo "::set-output name=exists::true"  # 파일이 존재하는 경우 'true'로 출력 설정
          else
            echo "::set-output name=exists::false"  # 파일이 존재하지 않는 경우 'false'로 출력 설정
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1 # Updated to latest version
        env:
          GITHUB_TOKEN: ${{ secrets.LONGTEA_GH }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1 # Updated to latest version
        env:
          GITHUB_TOKEN: ${{ secrets.LONGTEA_GH }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./longtea_${GITHUB_REF#refs/tags/}
          asset_name: longtea_${GITHUB_REF#refs/tags/}
          asset_content_type: application/octet-stream
